name: Setting up Go for testing
on:
  push:
jobs:
  setting-up-test:
    runs-on: ubuntu-16.04
    name: Go ${{ matrix.go }} example
    steps:
      - name: Creating checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
            go-version: '1.13.7'
      - name: checking go version
        run: go version
      - name: Install dependencies
        id: InstallDep
        run: |
          go get github.com/tebeka/go2xunit
      - if: ${{success()}}
        name: Go get go check
        run: |
          go get gopkg.in/check.v1
      - if: ${{success()}}
        name: Test using go check
        run: |
           go test -v
           2>&1 go test -v | go2xunit -output report.xml
      - if: ${{failure()}}
        name: Create issues if failed
        uses: nashmaniac/create-issue-action@v1.1 
        with:
          title: Build Failed
          token: ${{secrets.TOKEN_SECRET}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}}
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: report.xml